In [2]:
from keras.datasets import mnist
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics.cluster import rand_score


In [1]:
!pip install --upgrade scikit-learn


     |████████████████████████████████| 23.2 MB 1.7 MB/s 
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1


In [3]:
from sklearn import metrics

def purity_score(y_true, y_pred):
    contingency_matrix = metrics.cluster.contingency_matrix(y_true, y_pred)
    return np.sum(np.amax(contingency_matrix, axis=0)) / np.sum(contingency_matrix) 

In [4]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()


11501568/11490434 [==============================] - 0s 0us/step


In [5]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)
print(x_train.min())
print(x_train.max())
print(type(x_train))

(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)
0
255
<class 'numpy.ndarray'>


In [6]:
x_train = x_train.astype('float32') 
x_test = x_test.astype('float32')
# Normalization
x_train = x_train/255.0
x_test = x_test/255.0

In [7]:
X_train = x_train.reshape(len(x_train),-1)
X_test = x_test.reshape(len(x_test),-1)
print(X_train.shape)
print(X_test.shape)

(60000, 784)
(10000, 784)


k means

In [ ]:
from sklearn.cluster import KMeans

# kmeanModel1 = KMeans(n_clusters=10,init = 'k-means++')
kmeanModel1 = KMeans(n_clusters=10,n_init=5,max_iter=100,random_state=55,algorithm='auto',verbose=0)
kmeanModel1.fit(X_train)

KMeans(max_iter=100, n_clusters=10, n_init=5, random_state=55)

In [ ]:
y_kmeans1 = kmeanModel1.predict(X_train)
centers = kmeanModel1.cluster_centers_

In [ ]:
purity_score(y_train,y_kmeans1)

0.5910166666666666

In [ ]:
rand_score(y_kmeans1,y_train)

0.879543699061651

In [ ]:
kmeanModel2 = KMeans(n_clusters=10,init = 'random')
kmeanModel2.fit(X_train)

KMeans(init='random', n_clusters=10)

In [ ]:
y_kmeans2 = kmeanModel2.predict(X_train)
centers = kmeanModel2.cluster_centers_

In [ ]:
purity_score(y_train,y_kmeans2)

0.5909666666666666

In [ ]:
rand_score(y_kmeans2,y_train)

0.8795313488558143

K median


In [ ]:
!pip install scikit-learn-extra



     |████████████████████████████████| 1.7 MB 5.3 MB/s 


In [ ]:
from sklearn_extra.cluster import KMedoids
import numpy as np

In [ ]:
kmedoids = KMedoids(n_clusters=10, random_state=10).fit(X_train)
kmedoids.labels_


In [ ]:
array([0, 0, 0, 1, 1, 1])
kmedoids.predict([[0,0], [4,4]])
array([0, 1])
kmedoids.cluster_centers_
array([[1, 2],
       [4, 2]])
kmedoids.inertia_

mean shift

In [8]:
from sklearn.cluster import MeanShift
import numpy as np


In [16]:
clustering = MeanShift(bandwidth=10,bin_seeding = True).fit(X_train)
clustering.labels_


array([0, 0, 0, ..., 0, 0, 0])

In [17]:
purity_score(y_train,clustering.labels_)

0.11236666666666667

In [18]:
rand_score(clustering.labels_,y_train)

0.10027316399717773

DBSCAN

In [ ]:
from sklearn.cluster import DBSCAN


In [ ]:
clustering = DBSCAN(eps=2, min_samples=10).fit(X_train)
clustering.labels_

array([-1, -1, -1, ..., -1, -1, -1])

In [ ]:
purity_score(y_train,clustering.labels_)

0.16733333333333333

In [ ]:
rand_score(clustering.labels_,y_train)

0.20569828719367544

In [ ]:
clustering1 = DBSCAN(eps=3, min_samples=10).fit(X_train)
clustering1.labels_

array([-1, -1, -1, ..., -1, -1, -1])

In [ ]:
purity_score(y_train,clustering1.labels_)

0.20835

In [ ]:
rand_score(clustering1.labels_,y_train)

0.286215336922282

In [ ]:
clustering2 = DBSCAN(eps=5, min_samples=5).fit(X_train)
clustering2.labels_

array([-1,  0, -1, ...,  0,  0, -1])

In [ ]:
purity_score(y_train,clustering2.labels_)

0.19828333333333334

In [ ]:
rand_score(clustering2.labels_,y_train)

0.4836267743351278

In [ ]:
clustering3 = DBSCAN(eps=8, min_samples=5).fit(X_train)


In [ ]:
purity_score(y_train,clustering3.labels_)

0.11255

In [ ]:
rand_score(clustering3.labels_,y_train)

0.10070263782174148

**Agglomerative**

In [ ]:
from sklearn.cluster import AgglomerativeClustering
import numpy as np

In [ ]:
clustering = AgglomerativeClustering(n_clusters= 10, linkage='single').fit(X_train)

In [ ]:
clustering.labels_

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
purity_score(y_train,clustering.labels_)

0.11251666666666667

In [ ]:
rand_score(clustering.labels_,y_train)

0.10051444190736512

In [ ]:
clustering1 = AgglomerativeClustering(n_clusters= 10, linkage='average').fit(X_train)